/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;

CREATE TABLE `wp_aal_products` (
  `object_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `asin_locale` varchar(13) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `locale` varchar(4) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `modified_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `expiration_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `links` text COLLATE utf8mb4_unicode_520_ci,
  `rating` tinyint(3) unsigned DEFAULT NULL,
  `rating_image_url` text COLLATE utf8mb4_unicode_520_ci,
  `rating_html` blob,
  `currency` varchar(10) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `sales_rank` bigint(20) DEFAULT NULL,
  `price` bigint(20) unsigned DEFAULT NULL,
  `price_formatted` tinytext COLLATE utf8mb4_unicode_520_ci,
  `lowest_new_price` bigint(20) unsigned DEFAULT NULL,
  `lowest_new_price_formatted` tinytext COLLATE utf8mb4_unicode_520_ci,
  `lowest_used_price` bigint(20) unsigned DEFAULT NULL,
  `lowest_used_price_formatted` tinytext COLLATE utf8mb4_unicode_520_ci,
  `discounted_price` bigint(20) unsigned DEFAULT NULL,
  `discounted_price_formatted` tinytext COLLATE utf8mb4_unicode_520_ci,
  `count_new` bigint(20) unsigned DEFAULT NULL,
  `count_used` bigint(20) unsigned DEFAULT NULL,
  `title` text COLLATE utf8mb4_unicode_520_ci,
  `description` mediumtext COLLATE utf8mb4_unicode_520_ci,
  `images` mediumtext COLLATE utf8mb4_unicode_520_ci,
  `similar_products` mediumtext COLLATE utf8mb4_unicode_520_ci,
  `editorial_reviews` mediumblob,
  `customer_review_url` text COLLATE utf8mb4_unicode_520_ci,
  `customer_review_charset` varchar(20) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `customer_reviews` mediumblob,
  `number_of_reviews` bigint(20) unsigned DEFAULT NULL,
  `categories` text COLLATE utf8mb4_unicode_520_ci,
  `features` text COLLATE utf8mb4_unicode_520_ci,
  PRIMARY KEY (`object_id`),
  UNIQUE KEY `asin_locale` (`asin_locale`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
