<?php exit; ?>
[2020-01-05 23:34:00] ERROR: Form 1152 > Mailchimp API error: 401 Unauthorized. API Key Invalid. Your API key may be invalid, or you've attempted to access the wrong datacenter.
Request: GET https://us8.api.mailchimp.com/3.0/lists/5332ba9f20/members/9ee2e6fc715fb35dcc463be319c778df
Response: 401 Unauthorized - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"API Key Invalid","status":401,"detail":"Your API key may be invalid, or you've attempted to access the wrong datacenter.","instance":"f5380fb6-cb39-4f51-9c37-f2111bf1de10"}
[2020-01-05 23:37:17] ERROR: Form 1152 > Mailchimp API error: 401 Unauthorized. API Key Invalid. Your API key may be invalid, or you've attempted to access the wrong datacenter.
Request: GET https://us8.api.mailchimp.com/3.0/lists/5332ba9f20/members/9ee2e6fc715fb35dcc463be319c778df
Response: 401 Unauthorized - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"API Key Invalid","status":401,"detail":"Your API key may be invalid, or you've attempted to access the wrong datacenter.","instance":"46370f72-d95a-4fb2-bf70-c151fc687b74"}
[2020-01-05 23:46:13] ERROR: Form 1152 > Mailchimp API error: 401 Unauthorized. API Key Invalid. Your API key may be invalid, or you've attempted to access the wrong datacenter.
Request: GET https://us8.api.mailchimp.com/3.0/lists/5332ba9f20/members/9ee2e6fc715fb35dcc463be319c778df
Response: 401 Unauthorized - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"API Key Invalid","status":401,"detail":"Your API key may be invalid, or you've attempted to access the wrong datacenter.","instance":"3aef66ec-c7af-4afd-8784-973a30ac5228"}
[2020-01-05 23:46:23] ERROR: Form 1152 > Mailchimp API error: 401 Unauthorized. API Key Invalid. Your API key may be invalid, or you've attempted to access the wrong datacenter.
Request: GET https://us8.api.mailchimp.com/3.0/lists/5332ba9f20/members/9ee2e6fc715fb35dcc463be319c778df
Response: 401 Unauthorized - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"API Key Invalid","status":401,"detail":"Your API key may be invalid, or you've attempted to access the wrong datacenter.","instance":"74fafb24-7082-4c0d-b925-a30a56e6332d"}
[2020-01-05 23:46:52] ERROR: Form 1152 > Mailchimp API error: 401 Unauthorized. API Key Invalid. Your API key may be invalid, or you've attempted to access the wrong datacenter.
Request: GET https://us8.api.mailchimp.com/3.0/lists/5332ba9f20/members/54f66d9a3706c22554c0072ec6ceaab2
Response: 401 Unauthorized - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"API Key Invalid","status":401,"detail":"Your API key may be invalid, or you've attempted to access the wrong datacenter.","instance":"a9126ce0-5fcb-4f78-9270-a08b87acd46f"}
[2020-01-05 23:50:36] ERROR: Form 1152 > Mailchimp API error: 400 Bad Request. Forgotten Email Not Subscribed. diab**********@ya***.fr was permanently deleted and cannot be re-imported. The contact must re-subscribe to get back on the list.
Request: POST https://us8.api.mailchimp.com/3.0/lists/5332ba9f20/members - {"status":"pending","email_address":"diab**********@ya***.fr","interests":{},"merge_fields":{"FNAME":"Kelly","LNAME":"Diabagate"},"email_type":"html","ip_signup":"96.35.253.221","tags":[]}
Response: 400 Bad Request - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Forgotten Email Not Subscribed","status":400,"detail":"diab**********@ya***.fr was permanently deleted and cannot be re-imported. The contact must re-subscribe to get back on the list.","instance":"88fb36d4-9dd3-4c1f-bc90-adba92b3aaf2"}
[2020-01-05 23:59:22] ERROR: Form 1152 > Mailchimp API error: 400 Bad Request. Forgotten Email Not Subscribed. diab**********@ya***.fr was permanently deleted and cannot be re-imported. The contact must re-subscribe to get back on the list.
Request: POST https://us8.api.mailchimp.com/3.0/lists/5332ba9f20/members - {"status":"pending","email_address":"diab**********@ya***.fr","interests":{},"merge_fields":{"FNAME":"Kelly","LNAME":"Diabagate"},"email_type":"html","ip_signup":"96.35.253.221","tags":[]}
Response: 400 Bad Request - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Forgotten Email Not Subscribed","status":400,"detail":"diab**********@ya***.fr was permanently deleted and cannot be re-imported. The contact must re-subscribe to get back on the list.","instance":"12304abf-d462-4260-ad16-3674471f5850"}
[2020-01-06 00:02:36] ERROR: Form 1152 > Mailchimp API error: 400 Bad Request. Forgotten Email Not Subscribed. diab**********@ya***.fr was permanently deleted and cannot be re-imported. The contact must re-subscribe to get back on the list.
Request: POST https://us8.api.mailchimp.com/3.0/lists/5332ba9f20/members - {"status":"pending","email_address":"diab**********@ya***.fr","interests":{},"merge_fields":{"FNAME":"Kelly","LNAME":"Diabagate"},"email_type":"html","ip_signup":"96.35.253.221","tags":[]}
Response: 400 Bad Request - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Forgotten Email Not Subscribed","status":400,"detail":"diab**********@ya***.fr was permanently deleted and cannot be re-imported. The contact must re-subscribe to get back on the list.","instance":"38e3ff46-e91f-42af-9aed-98c8f1043638"}
[2020-01-06 00:04:35] ERROR: Form 1152 > Mailchimp API error: 400 Bad Request. Forgotten Email Not Subscribed. kell***********@gm***.com was permanently deleted and cannot be re-imported. The contact must re-subscribe to get back on the list.
Request: POST https://us8.api.mailchimp.com/3.0/lists/5332ba9f20/members - {"status":"pending","email_address":"kell***********@gm***.com","interests":{},"merge_fields":{"FNAME":"kelly","LNAME":"Diabagate"},"email_type":"html","ip_signup":"96.35.253.221","tags":[]}
Response: 400 Bad Request - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Forgotten Email Not Subscribed","status":400,"detail":"kell***********@gm***.com was permanently deleted and cannot be re-imported. The contact must re-subscribe to get back on the list.","instance":"2c40c470-2368-4548-8773-f8ebb8ac4b4a"}
[2020-01-06 00:09:02] ERROR: Form 1152 > Mailchimp API error: 400 Bad Request. Forgotten Email Not Subscribed. diab**********@ya***.fr was permanently deleted and cannot be re-imported. The contact must re-subscribe to get back on the list.
Request: POST https://us8.api.mailchimp.com/3.0/lists/5332ba9f20/members - {"status":"pending","email_address":"diab**********@ya***.fr","interests":{},"merge_fields":{"FNAME":"Kelly","LNAME":"Diabagate"},"email_type":"html","ip_signup":"96.35.253.221","tags":[]}
Response: 400 Bad Request - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Forgotten Email Not Subscribed","status":400,"detail":"diab**********@ya***.fr was permanently deleted and cannot be re-imported. The contact must re-subscribe to get back on the list.","instance":"94ae1329-b5de-45f2-889f-2a6641b256a7"}
